services:
  # API Monsters
  api_monsters:
    build:
      context: ./API_monstres
      dockerfile: Dockerfile
    container_name: api_monsters
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_monsters
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=monsters_db
    depends_on:
      - mongo_monsters
    networks:
      - api_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  
  mongo_monsters:
    image: mongo:latest
    container_name: mongo_monsters
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: monsters_db
    volumes:
      - mongo_monsters_data:/data/db
    networks:
      - api_network

  # API Joueur
  api_joueur:
    build:
      context: ./API_joueur
      dockerfile: Dockerfile
    container_name: api_joueur
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_player
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=gatcha-player-db
    depends_on:
      - mongo_player
    networks:
      - api_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo_player:
    image: mongo:latest
    container_name: mongo_player
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_DATABASE=gatcha-player-db
    volumes:
      - ./API_joueur/mongo-init:/docker-entrypoint-initdb.d
      - mongodb_player_data:/data/db
    networks:
      - api_network

  # API Invocations
  api_invocations:
    build:
      context: ./API_invocations
      dockerfile: Dockerfile
    container_name: api_invocations
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_invocations
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=api_invocationsdb
      - EXTERNAL_API_MONSTERS_BASE_URL=http://api_monsters:8080
      - EXTERNAL_API_PLAYER_BASE_URL=http://api_joueur:8080
      - EXTERNAL_API_CONNECTION_TIMEOUT=5000
      - EXTERNAL_API_READ_TIMEOUT=5000
    depends_on:
      - mongo_invocations
      - api_monsters
      - api_joueur
    networks:
      - api_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo_invocations:
    image: mongo:latest
    container_name: mongo_invocations
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: api_invocationsdb
    volumes:
      - mongo_invocations_data:/data/db
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  mongo_monsters_data:
  mongodb_player_data:
  mongo_invocations_data:
